"""empty message

Revision ID: 938af523634b
Revises: 
Create Date: 2025-08-06 11:13:23.389694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938af523634b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vehicles_mapped_model_id_fkey'), 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'mapped_model_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('mapped_model_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('vehicles_mapped_model_id_fkey'), 'vehicles', 'model_map', ['mapped_model_id'], ['id'])
    # ### end Alembic commands ###
